"""Add approved_by and approved_at to doctor_profiles

Revision ID: 604babfc4d0c
Revises: 09e69249b33b
Create Date: 2026-06-18 01:15:33.503632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '604babfc4d0c'
down_revision: Union[str, None] = '09e69249b33b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_profiles', sa.Column('approved_by', sa.UUID(), nullable=True))
    op.add_column('doctor_profiles', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'doctor_profiles', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'doctor_profiles', type_='foreignkey')
    op.drop_column('doctor_profiles', 'approved_at')
    op.drop_column('doctor_profiles', 'approved_by')
    # ### end Alembic commands ###
