"""Add video call fields to Appointment

Revision ID: 383466848a99
Revises: f0f74452029e
Create Date: 2026-06-22 11:53:15.714266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '383466848a99'
down_revision: Union[str, None] = 'f0f74452029e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('meeting_room_id', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('meeting_link_active', sa.Boolean(), nullable=True))
    op.create_unique_constraint(None, 'appointments', ['meeting_room_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_column('appointments', 'meeting_link_active')
    op.drop_column('appointments', 'meeting_room_id')
    # ### end Alembic commands ###
