"""Add KBDocument table

Revision ID: 81a6920bc096
Revises: 604babfc4d0c
Create Date: 2026-06-19 00:28:03.901746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector



# revision identifiers, used by Alembic.
revision: str = '81a6920bc096'
down_revision: Union[str, None] = '604babfc4d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT name FROM pg_available_extensions WHERE name = 'vector';")).fetchone()
    has_vector = result is not None

    if has_vector:
        op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
        embedding_type = pgvector.sqlalchemy.vector.VECTOR(dim=384)
    else:
        import logging
        logging.getLogger("alembic").warning("pgvector extension is not available on this database. Falling back to JSON for embedding.")
        embedding_type = sa.JSON()

    op.create_table('kb_documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('content_chunk', sa.String(), nullable=False),
    sa.Column('embedding', embedding_type, nullable=True),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    if has_vector:
        op.create_index('ix_kb_documents_embedding_ivfflat', 'kb_documents', ['embedding'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index(op.f('ix_kb_documents_id'), 'kb_documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_documents_id'), table_name='kb_documents')
    bind = op.get_bind()
    result = bind.execute(sa.text("SELECT name FROM pg_available_extensions WHERE name = 'vector';")).fetchone()
    if result is not None:
        op.drop_index('ix_kb_documents_embedding_ivfflat', table_name='kb_documents', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_table('kb_documents')
    # ### end Alembic commands ###
