"""Add appointment requests

Revision ID: e6d672cedc0a
Revises: 370693235a8a
Create Date: 2026-06-20 11:00:47.566519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d672cedc0a'
down_revision: Union[str, None] = '370693235a8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('triage_session_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PROPOSED', 'CONFIRMED', 'REJECTED', name='appointmentrequeststatus'), nullable=False),
    sa.Column('proposed_slot', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['triage_session_id'], ['triage_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_requests_id'), 'appointment_requests', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointment_requests_id'), table_name='appointment_requests')
    op.drop_table('appointment_requests')
    # ### end Alembic commands ###
